name: Push
on:
  push:
    branches: [ master ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: uk-policy-engine
          service_account_key: ${{ secrets.POLICYENGINE_UK_DATA_READ }}
          export_default_credentials: true
      - name: Install package
        run: make install
      - name: Download prerequisites
        run: openfisca-uk-data frs download 2018 & openfisca-uk-data ukmod_frs download 2018
      - name: Run tests
        run: make test
  Publish:
    if: github.repository == 'PSLmodels/openfisca-uk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Build package
        run: make
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
  BuildJB:
    name: Publish documentation
    needs: Test
    if: github.repository == 'PSLmodels/openfisca-uk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: openfisca_uk
          environment-file: docs/book/environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: uk-policy-engine
          service_account_key: ${{ secrets.POLICYENGINE_UK_DATA_READ }}
          export_default_credentials: true
      - name: Download prerequisites
        run: openfisca-uk-data frs download 2018 & openfisca-uk-data ukmod_frs download 2018
      - name: Run tests
        run: make test
      - name: Build
        shell: bash -l {0}
        run: |
          pip install -e .
          jb build docs/book/.
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/book/_build/html  # The folder the action should deploy.