name: Pull request
on:
  pull_request:
    branches: [ master ]
env:
  enhanced_frs: ${{ secrets.ENHANCED_FRS}}
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build changelog
        run: pip install yaml-changelog && make changelog
      - name: Preview changelog update
        run: ".github/get-changelog-diff.sh"
      - name: Check version number has been properly updated
        run: ".github/is-version-number-acceptable.sh"
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Wheel and Pytest
        run: pip3 install wheel setuptools pytest==5.4.3
      - name: Install libyaml
        run: pip3 uninstall pyyaml && pip3 install pyyaml --no-cache-dir
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: uk-policy-engine
          service_account_key: ${{ secrets.POLICYENGINE_UK_DATA_READ }}
          export_default_credentials: true
      - name: Install package
        run: make install
      - name: Set up tests
        run: make test-setup
      - name: Run tests
        run: make test
      - name: Generate documentation
        if: matrix.os == 'ubuntu-latest'
        run: make documentation
      - name: Print summary metrics
        run: python docs/summary/generate_summary.py
