name: Pull request
on:
  pull_request:
    branches: [ master ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Wheel and Pytest
        run: pip3 install wheel setuptools pytest==5.4.3
      - name: Install libyaml
        run: pip3 uninstall pyyaml && pip3 install pyyaml --no-cache-dir
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: uk-policy-engine
          service_account_key: ${{ secrets.POLICYENGINE_UK_DATA_READ }}
          export_default_credentials: true
      - name: Install package
        run: make install
      - name: Setup tests
        run: make test-setup
      - name: Run tests
        run: make test
      - name: Generate documentation
        if: matrix.os == 'ubuntu-latest'
        run: make documentation
