name: Pull request
on:
  pull_request:
    branches: [ master ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
      - name: Install Wheel and Pytest
        run: pip3 install wheel setuptools pytest==5.4.3
      - name: Install libyaml
        run: pip3 uninstall pyyaml && pip3 install pyyaml --no-cache-dir
      - name: Install package
        run: make install
      - name: Run tests
        run: make test
        env:
          POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN: ${{ secrets.POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN}}
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN}}
      - name: Generate documentation
        run: make documentation
        env:
          POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN: ${{ secrets.POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN}}
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN}}
      - name: Compare baseline change
        run: make compare_psnd
        env:
          POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN: ${{ secrets.POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN}}
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN}}
