# Workflow that runs on code changes to a pull request.

name: Docs changes
on:
  pull_request:
    branches:
      - master

    paths:
      - docs/**
      - .github/**

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Check formatting
          uses: "lgeiger/black-action@master"
          with:
              args: ". -l 79 --check"
  Test:
      runs-on: ubuntu-latest
      name: Test documentation builds
      steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Install uv
            uses: astral-sh/setup-uv@v5

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.12'
              
          - name: Install package
            run: uv pip install -e .[dev] --system
          - name: Install policyengine
            run: uv pip install policyengine --system
          - name: Test documentation builds
            run: make documentation