name: Push
on:
  push:
    branches: [ master ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'PolicyEngine/policyengine-uk')
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    runs-on: ${{ matrix.os }}
    if: |
      (github.repository == 'PolicyEngine/policyengine-uk')
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Wheel and Pytest
        run: pip3 install wheel setuptools pytest==5.4.3
      - name: Install libyaml
        run: pip3 uninstall pyyaml && pip3 install pyyaml --no-cache-dir
      - name: Install package
        run: make install
      - name: Run tests
        env:
          POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN: ${{ secrets.POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN}}
        run: make test
      - name: Generate documentation
        if: matrix.os == 'ubuntu-latest'
        run: make documentation
      - name: Deploy documentation
        if: matrix.os == 'ubuntu-latest'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/book/_build/html  # The folder the action should deploy.
  Publish:
    if: |
      (github.repository == 'PolicyEngine/policyengine-uk')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish a git tag
        run: ".github/publish-git-tag.sh"
      - name: Build package
        run: make
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          skip_existing: true
  Deploy:
    if: |
      (github.repository == 'PolicyEngine/policyengine-uk')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.POLICYENGINE_GITHUB }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.POLICYENGINE_GITHUB }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Wheel and Pytest
        run: pip3 install wheel setuptools pytest==5.4.3
      - name: Install package
        run: make install
      - name: Update API
        run: python .github/update_api.py
        env:
          GITHUB_TOKEN: ${{ secrets.POLICYENGINE_GITHUB }}
